language: node_js
node_js:
  - "6.9"
  - "node"
before_install:
  - npm install -g yarn
install:
  - yarn
  - cp ./src/config/loggly.js.sample ./src/config/loggly.js
  - cp ./src/config/sequelize.js.sample ./src/config/sequelize.js
script:
  - yarn run test
cache:
  directories:
    - $HOME/.yarn-cache
