steps:
  - name: ':hammer: Build'
    command: '/.buildkite/build.sh'
    agents:
      queue: 'elastic' 

  - name: ':fire: Test'
    command: '/.buildkite/test.sh'
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: app
      BUILDKITE_DOCKER_COMPOSE_FILE: docker-compose.buildkite.yml
    agents:
      queue: 'elastic'

  - wait

  - name: ':rocket: Deploy'
    command: '/.buildkite/deploy.sh'
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: app
      BUILDKITE_DOCKER_COMPOSE_FILE: docker-compose.buildkite.yml
    branches: 'develop staging master'
    agents:
      queue: 'elastic'

  #- wait

  #- name: ':fire: Prune'
  #  command: '/.buildkite/prune.sh'
  #  agents:
  #    queue: 'elastic'    